// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "kadaidemo1-20190218142213--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d1y4lu2zz6q69b.cloudfront.net"
};


export default awsmobile;
